Code smell fixes from SonarCloud analysis
examind-ai/ltijs-firestore pull request #7
Opened 2023-07-24 20:37 UTC by esinarta

### Overview

Fixed code smells using suggested changes from SonarCloud analysis while also testing automatic PR analysis scan.

### Changes

- Removed unused imports
- Replaced union types with type alias

2023-07-24 22:32 UTC, johnnyoshika requested changes

2023-07-24 22:32 UTC, johnnyoshika commented on src/IDatabase.ts
> +type DatabaseValue = string | number | boolean;
Let's call this `QueryValue`. Thanks!

2023-07-24 22:41 UTC, esinarta commented
@johnnyoshika renamed type alias to `QueryValue`

2023-07-25 15:29 UTC, johnnyoshika approved these changes

2023-07-25 15:29 UTC, merged